name: "Terraform Workflow"

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend-config="dev.config"

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform workspace select dev || terraform workspace new dev
          terraform plan -var-file="./environments/dev/terraform.tfvars" -out="dev.plan"

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply "dev.plan"
